# Change these first
owner: cmss13-devs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Internal - Analytics
    url: https://grafana.cm-ss13.com
    maxRedirects: 5
    expectedStatusCodes:
      - 200
      - 201
      - 202
      - 203
      - 200
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 400 # unsure why
      - 405 # unsure why
  - name: Internal - Authentication
    url: https://auth.cm-ss13.com
  - name: Internal - Game Management
    url: https://tgs.cm-ss13.com
  - name: Internal - Logs
    url: https://logs.cm-ss13.com
    expectedStatusCodes:
      - 200
      - 201
      - 202
      - 203
      - 200
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 400 # unsure why
      - 405 # unsure why
  - name: Internal - Raw Logs
    url: https://raw-logs.cm-ss13.com
    expectedStatusCodes:
      - 200
      - 201
      - 202
      - 203
      - 200
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 400 # unsure why
      - 405 # unsure why
  - name: All - Forums
    url: https://forum.cm-ss13.com
  - name: All - Website
    url: https://cm-ss13.com
  - name: All - Wiki
    url: https://cm-ss13.com/wiki
  - name: Relay - US East
    url: us-e.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - US West
    url: us-w.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - US NYC
    url: nyc.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - EU East
    url: eu-e.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - EU West
    url: eu-w.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - UK
    url: uk.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - AUS
    url: aus.cm-ss13.com
    port: 1400
    check: "tcp-ping"
  - name: Relay - ASIA-SE
    url: asia-se.cm-ss13.com
    port: 1400
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cm-ss13.com
  # baseUrl: /your-repo-name
  logoUrl: hhttps://cm-ss13.com/assets/logo.png
  name: CM-SS13 Status
  navbar:
    - title: Main Page
      href: https://cm-ss13.com/
    - title: Forums
      href: https://forum.cm-ss13.com
    - title: Status
      href: /
    - title: Game Repo
      href: https://github.com/$OWNER/cmss13-devs

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - hry-gh
